### ISSUE TITLE
enhancement request: add anchor link behind the app name to jump to the app store

### ISSUE THREAD

**Issue by j-ed** [nextcloud/caniupdate#11]
## Expected behavior
The list of apps should be structured similar to the app menu and it should be possible to jump directly to the app store if you click on a link anchor behind the app name.

## Current behavior
Only the app names itself are currently displayed and it isn't possible to jump directly to the app store.

## Mockup
![201712041-mockup](https://user-images.githubusercontent.com/2572764/33566188-78e52cde-d91f-11e7-9807-ee9cb210ae85.png)

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.4
Caniupdate app version: 0.1.1

#### Client Configuration
Browser: Mozilla Firefox 57.0.1
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Will publish an update on friday, so the new strings can be translated
