### ISSUE TITLE
Issue with Nc 13 Beta/RC1: claims it is 14

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/caniupdate#14]
As you can see in the screenshot, I run a beta of Nc 13 and there is an upgrade for RC 1 available. Can-I-Update claims that I shouldn't as most apps are not available for Nextcloud 14, which is probably true but not really something I care about right now 😄 
![screenshot_20180116_221121](https://user-images.githubusercontent.com/551757/35012501-3b3757ce-fb0a-11e7-9769-e075da60f541.png)

**Comment by jospoortvliet** [comment]
BTW I have not yet updated so if you figure out what the problem is I can help test it :D

**Comment by nickvergessen** [comment]
Well i just take the major and do +1
I will simply ship an update which hardcodes it to check against 13, because it only checks for majors anyway

**Comment by nickvergessen** [comment]
Will publish an update on friday, so the new strings can be translated
