### ISSUE TITLE
Link from the app page to "Ask Questions or Discuss" goes to a private page in the forums

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/caniupdate#24]
At https://apps.nextcloud.com/apps/caniupdate there is a link to "Ask questions or discuss" to https://help.nextcloud.com/c/apps/caniupdate.

This is in the forums, but an error message indicates: "Oops! That page doesn’t exist or is private.".

**Comment by nickvergessen** [comment]
Since this app discontinued because it was merged with another one i dont care too much
