### ISSUE TITLE
Removing translation resource from Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/caniupdate#26]
The app looks deprecated.
So I would like to remove the resource from Transifex.

If you ask why? See https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312

Existing translations are not lost. They will remain in this repository.

@MorrisJobke @rullzer Are there any objections on your part?

btw. No action needed from your side. My rights at Transifex are sufficient to do this.

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
The app is part of server since 14 or 15, so should be okay to remove it

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/docker-ci/commit/02b3042424e6196c193be11a34f582bda4061849
