### ISSUE TITLE
Remove this app from apps.nextcloud.com

### ISSUE THREAD

**Issue by p-bo** [nextcloud/caniupdate#27]
Hello,
because this app is not existing any more (its function was integrated into server itself, as stated), would it be possible to remove it from app catalogue to clean up please?

Instructions how to do it:
https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

Thanks :-)

**Comment by nickvergessen** [comment]
Could still serve as a sample and it can help people on old versions (but then again, it might not be useful as if an app doesn't have an update by now, it will not get it in a forseeable future.

**Comment by p-bo** [comment]
> Could still serve as a sample

Definitely - but problem is, that in meantime there is no way how to filter out such (archived) applications in Applications catalogue on Nextcloud instance - so it is really crowded by them.

There was even request to implement filtering by Nextcloud version supported for apps.nextcloud.com, but never materialized:
https://github.com/nextcloud/appstore/issues/412
It could be, that similar request was done for its sibling at Nextcloud server
https://github.com/nextcloud/server/issues
but not able to found it among thousands of issues.

Right now, when one get either to apps.nextloud.com or (especially there) open Applications section on Nextcloud instance, is overwhelmed by list of defunct apps and must "filter" only by eyes, which is not pleasant experience.

> it can help people on old versions

According app page, last version supported is Nexcloud 14
https://apps.nextcloud.com/apps/caniupdate
But even Enterprise support is 5 years.
https://nextcloud.com/industries/enterprise/
"Security updates | For up to 5 years"

And Nextcloud 14 was released 09/2018
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Thus 09/2018 + 5 years = 09/2023 - so maybe what about to schedule app store page removal to 10/2023, to be on safe side?

**Comment by nickvergessen** [comment]
I will speak to the responsible persons and then follow up to the topic or not depending on the decision.

**Comment by p-bo** [comment]
Great, thank you so much for raising this topic among Nextcloud devs!

As support material for that discussion, there were even more requests to app filtering by Nextcloud version supported - for instance:

https://help.nextcloud.com/t/is-it-possible-to-have-a-nc-server-version-filter-on-appstore-site/95028/4
https://help.nextcloud.com/t/apps-compatible-with-wich-version-list-filter/101903
https://help.nextcloud.com/t/app-store-new-filter-option-available-for-major-release-x/123229
