### ISSUE TITLE
Some text strings cannot be translated yet

### ISSUE THREAD

**Issue by j-ed** [nextcloud/caniupdate#8]
## Expected behavior
All text elements should be translated into local languages.

## Current behavior
The following text strings are not yet translatable:
```
/js/components/root.js: 18:Can I update?
                        26:Missing updates
                        32:Available updates
```
### Steps to reproduce
1. Open `Admin -> Basic settings -> Can I update?`.
2. Check the translations if a non english language has been selected.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.3
Caniupdate app version: 0.1.0

#### Client Configuration
Browser: Mozilla Firefox 57.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Thanks again for the report, should be fixed with the newest release
